//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH_Database.Ressources.Pictures.Rarities.MHW {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Weapons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Weapons() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MH_Database.Ressources.Pictures.Rarities.MHW.Weapons", typeof(Weapons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_1_bow_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_1_bow_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_1_charge_blade_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_1_charge_blade_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_1_culldrone_kinsect_tree {
            get {
                object obj = ResourceManager.GetObject("rare_1_culldrone_kinsect_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_1_dual_blades_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_1_dual_blades_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_1_greatsword_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_1_greatsword_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_1_gunlance_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_1_gunlance_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_1_hammer_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_1_hammer_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_1_heavy_bowgun_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_1_heavy_bowgun_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_1_hunting_horn_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_1_hunting_horn_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_1_insect_glaive_mhw_tree_tree {
            get {
                object obj = ResourceManager.GetObject("rare_1_insect_glaive_mhw_tree_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_1_lance_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_1_lance_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_1_light_bowgun_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_1_light_bowgun_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_1_longsword_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_1_longsword_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_1_mauldrone_kinsect_tree {
            get {
                object obj = ResourceManager.GetObject("rare_1_mauldrone_kinsect_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_1_switch_axe_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_1_switch_axe_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_1_sword_shield_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_1_sword_shield_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_10_mhw_bow_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_10_mhw_bow_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_10_mhw_charge_blade_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_10_mhw_charge_blade_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_10_mhw_dualblades_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_10_mhw_dualblades_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_10_mhw_greatsword_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_10_mhw_greatsword_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_10_mhw_gunlance_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_10_mhw_gunlance_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_10_mhw_hammer_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_10_mhw_hammer_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_10_mhw_heavybow_gun_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_10_mhw_heavybow_gun_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_10_mhw_hunting_horn_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_10_mhw_hunting_horn_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_10_mhw_insect_glaive_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_10_mhw_insect_glaive_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_10_mhw_kinsect_wiki1 {
            get {
                object obj = ResourceManager.GetObject("rare_10_mhw_kinsect_wiki1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_10_mhw_lance_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_10_mhw_lance_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_10_mhw_light_bowgun_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_10_mhw_light_bowgun_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_10_mhw_longsword_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_10_mhw_longsword_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_10_mhw_switch_axe_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_10_mhw_switch_axe_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_10_mhw_sword_shield_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_10_mhw_sword_shield_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_11_mhw_bow_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_11_mhw_bow_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_11_mhw_charge_blade_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_11_mhw_charge_blade_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_11_mhw_dualblades_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_11_mhw_dualblades_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_11_mhw_greatsword_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_11_mhw_greatsword_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_11_mhw_gunlance_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_11_mhw_gunlance_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_11_mhw_hammer_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_11_mhw_hammer_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_11_mhw_heavybow_gun_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_11_mhw_heavybow_gun_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_11_mhw_hunting_horn_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_11_mhw_hunting_horn_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_11_mhw_insect_glaive_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_11_mhw_insect_glaive_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_11_mhw_lance_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_11_mhw_lance_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_11_mhw_light_bowgun_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_11_mhw_light_bowgun_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_11_mhw_longsword_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_11_mhw_longsword_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_11_mhw_switch_axe_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_11_mhw_switch_axe_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_11_mhw_sword_shield_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_11_mhw_sword_shield_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_12_mhw_bow_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_12_mhw_bow_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_12_mhw_charge_blade_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_12_mhw_charge_blade_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_12_mhw_dualblades_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_12_mhw_dualblades_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_12_mhw_greatsword_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_12_mhw_greatsword_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_12_mhw_gunlance_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_12_mhw_gunlance_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_12_mhw_hammer_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_12_mhw_hammer_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_12_mhw_heavybow_gun_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_12_mhw_heavybow_gun_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_12_mhw_hunting_horn_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_12_mhw_hunting_horn_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_12_mhw_insect_glaive_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_12_mhw_insect_glaive_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_12_mhw_kinsect_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_12_mhw_kinsect_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_12_mhw_lance_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_12_mhw_lance_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_12_mhw_light_bowgun_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_12_mhw_light_bowgun_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_12_mhw_longsword_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_12_mhw_longsword_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_12_mhw_switch_axe_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_12_mhw_switch_axe_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_12_mhw_sword_shield_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_12_mhw_sword_shield_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_2_bow_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_2_bow_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_2_charge_blade_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_2_charge_blade_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_2_culldrone_kinsect_tree {
            get {
                object obj = ResourceManager.GetObject("rare_2_culldrone_kinsect_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_2_dual_blades_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_2_dual_blades_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_2_greatsword_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_2_greatsword_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_2_gunlance_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_2_gunlance_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_2_hammer_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_2_hammer_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_2_heavy_bowgun_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_2_heavy_bowgun_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_2_hunting_horn_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_2_hunting_horn_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_2_insect_glaive_mhw_tree_tree {
            get {
                object obj = ResourceManager.GetObject("rare_2_insect_glaive_mhw_tree_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_2_lance_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_2_lance_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_2_light_bowgun_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_2_light_bowgun_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_2_longsword_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_2_longsword_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_2_mauldrone_kinsect_tree {
            get {
                object obj = ResourceManager.GetObject("rare_2_mauldrone_kinsect_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_2_switch_axe_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_2_switch_axe_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_2_sword_shield_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_2_sword_shield_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_3_bow_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_3_bow_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_3_charge_blade_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_3_charge_blade_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_3_culldrone_kinsect_tree {
            get {
                object obj = ResourceManager.GetObject("rare_3_culldrone_kinsect_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_3_dual_blades_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_3_dual_blades_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_3_greatsword_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_3_greatsword_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_3_gunlance_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_3_gunlance_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_3_hammer_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_3_hammer_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_3_heavy_bowgun_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_3_heavy_bowgun_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_3_hunting_horn_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_3_hunting_horn_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_3_insect_glaive_mhw_tree_tree {
            get {
                object obj = ResourceManager.GetObject("rare_3_insect_glaive_mhw_tree_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_3_lance_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_3_lance_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_3_light_bowgun_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_3_light_bowgun_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_3_longsword_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_3_longsword_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_3_mauldrone_kinsect_tree {
            get {
                object obj = ResourceManager.GetObject("rare_3_mauldrone_kinsect_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_3_switch_axe_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_3_switch_axe_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_3_sword_shield_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_3_sword_shield_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_4_bow_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_4_bow_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_4_charge_blade_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_4_charge_blade_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_4_culldrone_kinsect_tree {
            get {
                object obj = ResourceManager.GetObject("rare_4_culldrone_kinsect_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_4_dual_blades_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_4_dual_blades_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_4_greatsword_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_4_greatsword_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_4_gunlance_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_4_gunlance_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_4_hammer_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_4_hammer_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_4_heavy_bowgun_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_4_heavy_bowgun_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_4_hunting_horn_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_4_hunting_horn_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_4_insect_glaive_mhw_tree_tree {
            get {
                object obj = ResourceManager.GetObject("rare_4_insect_glaive_mhw_tree_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_4_lance_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_4_lance_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_4_light_bowgun_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_4_light_bowgun_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_4_longsword_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_4_longsword_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_4_mauldrone_kinsect_tree {
            get {
                object obj = ResourceManager.GetObject("rare_4_mauldrone_kinsect_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_4_switch_axe_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_4_switch_axe_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_4_sword_shield_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_4_sword_shield_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_5_bow_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_5_bow_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_5_charge_blade_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_5_charge_blade_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_5_culldrone_kinsect_tree {
            get {
                object obj = ResourceManager.GetObject("rare_5_culldrone_kinsect_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_5_dual_blades_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_5_dual_blades_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_5_greatsword_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_5_greatsword_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_5_gunlance_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_5_gunlance_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_5_hammer_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_5_hammer_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_5_heavy_bowgun_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_5_heavy_bowgun_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_5_hunting_horn_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_5_hunting_horn_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_5_insect_glaive_mhw_tree_tree {
            get {
                object obj = ResourceManager.GetObject("rare_5_insect_glaive_mhw_tree_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_5_lance_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_5_lance_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_5_light_bowgun_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_5_light_bowgun_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_5_longsword_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_5_longsword_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_5_mauldrone_kinsect_tree {
            get {
                object obj = ResourceManager.GetObject("rare_5_mauldrone_kinsect_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_5_switch_axe_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_5_switch_axe_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_5_sword_shield_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_5_sword_shield_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_6_bow_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_6_bow_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_6_charge_blade_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_6_charge_blade_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_6_culldrone_kinsect_tree {
            get {
                object obj = ResourceManager.GetObject("rare_6_culldrone_kinsect_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_6_dual_blades_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_6_dual_blades_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_6_greatsword_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_6_greatsword_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_6_gunlance_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_6_gunlance_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_6_hammer_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_6_hammer_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_6_heavy_bowgun_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_6_heavy_bowgun_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_6_hunting_horn_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_6_hunting_horn_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_6_insect_glaive_mhw_tree_tree {
            get {
                object obj = ResourceManager.GetObject("rare_6_insect_glaive_mhw_tree_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_6_lance_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_6_lance_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_6_light_bowgun_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_6_light_bowgun_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_6_longsword_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_6_longsword_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_6_mauldrone_kinsect_tree {
            get {
                object obj = ResourceManager.GetObject("rare_6_mauldrone_kinsect_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_6_switch_axe_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_6_switch_axe_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_6_sword_shield_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_6_sword_shield_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_7_bow_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_7_bow_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_7_charge_blade_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_7_charge_blade_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_7_culldrone_kinsect_tree {
            get {
                object obj = ResourceManager.GetObject("rare_7_culldrone_kinsect_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_7_dual_blades_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_7_dual_blades_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_7_greatsword_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_7_greatsword_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_7_gunlance_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_7_gunlance_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_7_hammer_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_7_hammer_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_7_heavy_bowgun_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_7_heavy_bowgun_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_7_hunting_horn_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_7_hunting_horn_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_7_insect_glaive_mhw_tree_tree {
            get {
                object obj = ResourceManager.GetObject("rare_7_insect_glaive_mhw_tree_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_7_lance_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_7_lance_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_7_light_bowgun_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_7_light_bowgun_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_7_longsword_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_7_longsword_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_7_mauldrone_kinsect_tree {
            get {
                object obj = ResourceManager.GetObject("rare_7_mauldrone_kinsect_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_7_switch_axe_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_7_switch_axe_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_7_sword_shield_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_7_sword_shield_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_8_bow_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_8_bow_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_8_charge_blade_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_8_charge_blade_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_8_dual_blades_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_8_dual_blades_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_8_greatsword_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_8_greatsword_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_8_gunlance_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_8_gunlance_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_8_hammer_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_8_hammer_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_8_heavy_bowgun_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_8_heavy_bowgun_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_8_hunting_horn_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_8_hunting_horn_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_8_insect_glaive_mhw_tree_tree {
            get {
                object obj = ResourceManager.GetObject("rare_8_insect_glaive_mhw_tree_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_8_lance_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_8_lance_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_8_light_bowgun_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_8_light_bowgun_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_8_longsword_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_8_longsword_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_8_switch_axe_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_8_switch_axe_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_8_sword_shield_mhw_tree {
            get {
                object obj = ResourceManager.GetObject("rare_8_sword_shield_mhw_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_9_mhw_bow_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_9_mhw_bow_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_9_mhw_charge_blade_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_9_mhw_charge_blade_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_9_mhw_dualblades_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_9_mhw_dualblades_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_9_mhw_greatsword_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_9_mhw_greatsword_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_9_mhw_gunlance_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_9_mhw_gunlance_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_9_mhw_hammer_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_9_mhw_hammer_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_9_mhw_heavybow_gun_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_9_mhw_heavybow_gun_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_9_mhw_hunting_horn_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_9_mhw_hunting_horn_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_9_mhw_insect_glaive_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_9_mhw_insect_glaive_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_9_mhw_kinsect_wiki1 {
            get {
                object obj = ResourceManager.GetObject("rare_9_mhw_kinsect_wiki1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_9_mhw_lance_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_9_mhw_lance_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_9_mhw_light_bowgun_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_9_mhw_light_bowgun_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_9_mhw_longsword_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_9_mhw_longsword_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_9_mhw_switch_axe_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_9_mhw_switch_axe_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rare_9_mhw_sword_shield_wiki {
            get {
                object obj = ResourceManager.GetObject("rare_9_mhw_sword_shield_wiki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
